[project]
name = "agent-client"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi>=0.116.1",
    "flask>=3.1.1",
    "flask-cors>=6.0.1",
    "mcp[cli]>=1.12.0",
    "openai>=1.97.1",
    "requests>=2.32.4",
]
