[project]
name = "chat-with-graph-system"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi>=0.116.1",
    "jinja2>=3.1.6",
    "mcp[cli]>=1.12.2",
    "openai>=1.97.1",
]
